Vagrant.configure(2) do |config|

  config.vm.box = "debian/stretch64"

  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
  end
  
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get install -y git clang cmake pkg-config javascriptcoregtk-4.0 libglib2.0-dev libzip-dev libcurl4-gnutls-dev libicu-dev default-jdk maven curl unzip
    mkdir bin
    curl -L https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein > bin/lein
    chmod +x bin/lein
  SHELL

end
