Vagrant.configure(2) do |config|

  config.vm.box = "centos/7"
  
  config.vm.provision "shell", inline: <<-SHELL
    sudo yum -y install git gcc cmake java maven webkitgtk3-devel libzip-devel libcurl-devel vim unzip
    curl -O https://download.clojure.org/install/linux-install-1.9.0.358.sh
    chmod +x linux-install-1.9.0.358.sh
    sudo ./linux-install-1.9.0.358.sh
  SHELL

end
