Vagrant.configure(2) do |config|

  config.vm.box = "debian/jessie64"

  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
  end
  
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get install -y git clang cmake pkg-config javascriptcoregtk-4.0 libglib2.0-dev libzip-dev libcurl4-gnutls-dev libicu-dev default-jdk maven curl
    curl -O https://download.clojure.org/install/linux-install-1.9.0.315.sh
    chmod +x linux-install-1.9.0.315.sh
    sudo ./linux-install-1.9.0.315.sh
  SHELL

end
