.\"to render: groff -Tascii -man planck-man/planck.1 > planck.man"
.TH PLANCK 1 "2019 April 6"
.SH NAME
plk, planck \- Planck REPL

.SH SYNOPSIS

.B plk
[\fBdep-opts...\fR] [\fBinit-opts...\fR] [\fBmain-opt\fR]
[\fBargs...\fR]
.br
.B planck
[\fBinit-opts...\fR] [\fBmain-opt\fR]
[\fBargs...\fR]

.SH DESCRIPTION

The
.B planck
binary is a self-hosted ClojureScript REPL and script runner.
The
.B plk
script is a wrapper around
.B planck
that delegates to clojure(1) to provide support for dependency
management via
.B dep-opts
processing.

The
.B plk
script ultimately constructs and invokes a command-line of the form:

.B planck
--classpath classpath [\fBinit-opts...\fR] [\fBmain-opt\fR] [\fBargs...\fR]

.SH EXAMPLES

You can launch a ClojureScript REPL by running
.BR plk .

See the Planck User Guide below for more complex usage.

.SH OPTIONS

The
.B plk
script can take three types of options, as shown in the
synopsis.
.B dep-opts
are used to build the 
classpath.
.B init-opts
specify configuration options or refer to ClojureScript 
code to execute.
.B main-opt
identifies the main ClojureScript code to execute or
indicates that a REPL should be launched.

The
.B planck
binary supports the same except that
.B dep-opts
is not supported.

.SS dep-opts

.TP
.BI \-R: alias
Concatenated resolve-deps aliases, ex: -R:bench:1.9

.TP
.BI \-C: alias
Concatenated make-classpath aliases, ex: -C:dev

.TP
.BI \-M: alias
Concatenated main option aliases, ex: -M:test

.TP
.BI \-A: alias
Concatenated aliases of any kind, ex: -A:dev:mem

.TP
.BI \-Sdeps\  EDN
Deps data to use as the final deps file

.TP
.BI \-Spath
Compute classpath and echo to stdout only

.TP
.BI \-Scp\  CP
Do NOT compute or cache classpath, use this one instead

.TP
.BI \-Srepro
Ignore the ~/.clojure/deps.edn config file

.TP
.BI \-Sforce
Force recomputation of the classpath (don't use the cache)

.TP
.BI \-Spom
Generate (or update existing) pom.xml with deps and paths

.TP
.BI \-Stree
Print dependency tree

.TP
.BI \-Sresolve-tags
Resolve git coordinate tags to shas and update deps.edn

.TP
.BI \-Sverbose
Print important path info to console

.TP
.BI \-Sdescribe
Print environment and command parsing info as data

.P
Additionally, for compatibility with clojure(1),
.B -Jopt
and 
.B -Oalias...
.B dep-opts
are accepted but ignored.

.SS init-opts

.TP
.BR \-co ", " \-\-compile-opts\  \fIedn\fR
Options to configure compilation, can be an EDN
string or colon-separated list of EDN files /
classpath resources. Options will be merged left
to right.

.TP
.BR \-i ", " \-\-init\  \fIpath\fR
Load a file or resource

.TP
.BR \-e ", " \-\-eval\  \fIstring\fR
Eval exprs in \fIstring\fR; print non-nil values

.TP
.BR \-c ", " \-\-classpath\  \fIcp\fR
Use colon-delimited \fIcp\fR for source directories
and JARs. PLANCK_CLASSPATH env var may be used
instead.

.TP
.BR \-D ", " \-\-dependencies\  \fIdep\fR
Use comma-separated list of dependencies to
look for in the local Maven repository.
Dependencies should be specified in the form
SYM:VERSION (e.g.: foo/bar:1.2.3).

.TP
.BR \-L ", " \-\-local-repo\  \fIpath\fR
Path to the local Maven repository where Planck
will look for dependencies. Defaults to
~/.m2/repository.

.TP
.BR \-K ", " \-\-auto-cache\ 
Create and use .planck_cache dir for cache

.TP
.BR \-k ", " \-\-cache\  \fIpath\fR
If dir exists at \fIpath\fR, use it for cache

.TP
.BR \-q ", " \-\-quiet\ 
Quiet mode

.TP
.BR \-v ", " \-\-verbose\ 
Emit verbose diagnostic output

.TP
.BR \-d ", " \-\-dumb-terminal\ 
Disable line editing / VT100 terminal control

.TP
.BR \-t ", " \-\-theme\  \fItheme\fR
Set the color theme

.TP
.BR \-n ", " \-\-socketrepl\  \fIx\fR
Enable socket REPL where \fIx\fR is port or IP:port

.TP
.BR \-s ", " \-\-static-fns\ 
Generate static dispatch function calls

.TP
.BR \-f ", " \-\-fn-invoke-direct\ 
Do not not generate .call(null...) calls
for unknown functions, but instead direct
invokes via f(a0,a1...)

.TP
.BR \-O ", " \-\-optimizations\  \fIlevel\fR
Closure compiler \fIlevel\fR applied to source loaded
from namespaces: none, whitespace, or simple. If using the
.B plk
script, the long form of this option must be used.

.TP
.BR \-A ", " \-\-checked-arrays\  \fIx\fR
Enables checked arrays where \fIx\fR is either warn
or error. If using the
.B plk
script, the long form of this option must be used.

.TP
.BR \-a ", " \-\-elide-asserts\ 
Set *assert* to false to remove asserts

.SS main-opts

.TP
.BR \-m ", " \-\-main\  \fIns-name \fR
Call the -main function from namespace with args

.TP
.BR \-r ", " \-\-repl
Run a repl

.TP
.I path
Run a script from a file or resource located at \fIpath\fR

.TP
.B \-
Run a script from standard input

.TP
.BR \-h ", " \-? ", " \-\-help
Print this help message and exit

.TP
.BR \-l ", " \-\-legal
Show legal info (licenses and copyrights)

.TP
.BR \-V ", " \-\-version
Show version and exit

.SH CONFIGURATION

The
.B plk
script reads configuration from
.B deps.edn
files. It will check against
.B deps.edn
files in the system default location, the configuration
directory (usually
.BR ~/.clojure ),
and the local directory. Files in each of these locations, if
they exist, are merged to form one combined configuration
file. The last specified configuration file's options
overwrites any earlier files (e.g. local configs take
priority).

.SH SEE ALSO

.IP http://planck-repl.org
Planck
.IP http://planck-repl.org/guide.html
Planck User Guide
.IP https://clojure.org/guides/deps_and_cli
Deps and CLI Guide
.IP https://clojure.org/reference/deps_and_cli
Deps and CLI Reference

.SH BUGS

Visit the bug tracker at
https://github.com/planck-repl/planck/issues to file an issue.

.SH AUTHORS

.B planck
and 
.B plk
are maintained by Mike Fikes <mike@fikesfarm.com>.

.SH COPYRIGHT

Copyright \(co 2015-2019 Mike Fikes and Contributors.

Distributed under the Eclipse Public License either 
version 1.0 or (at your option) any later version.
