#!/bin/bash

source int-test/script/setup-env-c
int-test/script/gen-actual > $ACTUAL_PATH/PLANCK-OUT.txt 2> $ACTUAL_PATH/PLANCK-ERR.txt
#int-test/script/int-tests 
diff $EXPECTED_PATH/PLANCK-OUT.txt $ACTUAL_PATH/PLANCK-OUT.txt && diff $EXPECTED_PATH/PLANCK-ERR.txt $ACTUAL_PATH/PLANCK-ERR.txt 
