#!/usr/bin/env bash

if [ "${VERBOSE_BUILD:-0}" == "1" ]; then
  set -x
fi

if [ -z "$BUILD_PPA" ]; then
    rm -rf compiler
fi

cd planck-cljs
script/clean
cd ..

# CMake
rm -rf planck-c/build

# Site
cd site
script/clean
cd ..
