#!/usr/bin/env bash
set -e -o pipefail

if [ "${VERBOSE_BUILD:-0}" == "1" ]; then
  set -x
fi

if [ ! -f compiler/closure-compiler-v$GCC_RELEASE.jar ]; then
  echo "Fetching Google Closure Compiler..."
  mkdir -p compiler
  cd compiler
  curl --retry 3 -O -s https://dl.google.com/closure-compiler/compiler-$GCC_RELEASE.zip || { echo "Download failed."; exit 1; }
  unzip -qu compiler-$GCC_RELEASE.zip
  echo "Cleaning up Google Closure Compiler archive..."
  rm compiler-$GCC_RELEASE.zip
  cd ../..
fi
