#!/usr/bin/env bash

if [ "${VERBOSE_BUILD:-0}" == "1" ]; then
  set -x
fi

if [ ! -f compiler/closure-compiler-v$GCC_RELEASE.jar ]; then
  echo "Fetching Google Closure Compiler..."
  mkdir -p compiler
  cd compiler
  curl --retry 3 -O -s https://repo1.maven.org/maven2/com/google/javascript/closure-compiler/v$GCC_RELEASE/closure-compiler-v$GCC_RELEASE.jar || { echo "Download failed."; exit 1; }
  cd ../..
fi
