#!/usr/bin/env bash
mkdir -p lib
if [ ! -f lib/test.check-0.10.0-alpha2.jar ]; then
  cp ~/.m2/repository/org/clojure/test.check/0.10.0-alpha2/test.check-0.10.0-alpha2.jar lib/test.check-0.10.0-alpha2.jar
fi
