#!/usr/bin/env bash
set -e -o pipefail

if [ "${VERBOSE_BUILD:-0}" == "1" ]; then
  set -x
fi

mkdir -p lib
version=3.0.3-1
if [ ! -f lib/long-$version.jar ]; then
  cp ~/.m2/repository/cljsjs/long/$version/long-$version.jar lib/long-$version.jar
fi
