#!/usr/bin/env bash
set -e -o pipefail

if [ "${VERBOSE_BUILD:-0}" == "1" ]; then
  set -x
fi

if [ ! -d planck-cljs/.buildcache-$GCC_RELEASE-$GCL_RELEASE ]; then
  echo "Fetching Build Cache..."
  cd planck-cljs
  curl --retry 3 -O -s https://planck-repl.org/releases/buildcache-$GCC_RELEASE-$GCL_RELEASE.tar || { echo "Download failed."; exit 1; }
  tar -xf buildcache-$GCC_RELEASE-$GCL_RELEASE.tar
  echo "Cleaning up Build Cache archive..."
  rm buildcache-$GCC_RELEASE-$GCL_RELEASE.tar
  cd ..
fi
