#!/usr/bin/env bash

if [ "${VERBOSE_BUILD:-0}" == "1" ]; then
  set -x
fi

mkdir -p lib
if [ ! -f lib/speculative-0.0.2.jar ]; then
  cp ~/.m2/repository/speculative/speculative/0.0.2/speculative-0.0.2.jar lib/speculative-0.0.2.jar
fi
