#!/usr/bin/env bash

if [ "${VERBOSE_BUILD:-0}" == "1" ]; then
  set -x
fi

output=planck-cljs/src/planck/bundle/gcl.cljs

if [ ! -f $output ]; then

  echo "Fetching Google Closure Library..."

  if ! [ -d planck-cljs/lib/closure ]; then
    mkdir -p planck-cljs/lib/closure
    cd planck-cljs/lib/closure
    curl --retry 3 -LO -s https://repo1.maven.org/maven2/org/clojure/google-closure-library/$GCL_RELEASE/google-closure-library-$GCL_RELEASE.jar || { echo "Download failed."; exit 1; }
    jar xf google-closure-library-$GCL_RELEASE.jar
    rm google-closure-library-$GCL_RELEASE.jar
    cd ..
    mkdir -p third_party/closure
    cd third_party/closure
    curl --retry 3 -O -s https://repo1.maven.org/maven2/org/clojure/google-closure-library-third-party/$GCL_RELEASE/google-closure-library-third-party-$GCL_RELEASE.jar || { echo "Download failed."; exit 1; }
    jar xf google-closure-library-third-party-$GCL_RELEASE.jar
    rm google-closure-library-third-party-$GCL_RELEASE.jar
    cd ../..
    cd ../..
  fi

  mkdir -p planck-cljs/src/planck/bundle

  cat <<EOF > $output
(ns planck.bundle.gcl
  "Require the namespaces that make up the Google Closure Library."
  (:require
EOF

  cd planck-cljs/lib/closure/goog
  for ns in `find . -path './debug' -prune \
                -or -path './demos' -prune \
                -or -path './editor' -prune \
                -or -path './events' -prune \
                -or -path './fx' -prune \
                -or -path './graphics' -prune \
                -or -path './labs' -prune \
                -or -path './messaging/testdata' -prune \
                -or -path './module/testdata' -prune \
                -or -path './net/testdata' -prune \
                -or -path './testing' -prune \
                -or -path './ui' -prune \
                -or -name '*.js' \
                -not -name '*_test.js' \
                -exec sed -n "s/^goog\.provide('\(goog\...*\)');$/\1/p" {} \; | \
             sort -u`
  do
    if [[ ! "$ns" =~ i18n.*_[A-Za-z][A-Za-z] ]]
    then
      cat <<EOF >> ../../../../$output
   [$ns]
EOF
    fi
  done
  cd ../../../..

  cd planck-cljs/lib/third_party/closure/goog
  for ns in `find . -path './svgpan' -prune \
                -or -name '*.js' \
                -not -name '*_test.js' \
                -exec sed -n "s/^goog\.provide('\(goog\...*\)');$/\1/p" {} \; | \
             sort -u`
  do
    cat <<EOF >> ../../../../../$output
   [$ns]
EOF
  done
  cd ../../../../..

  cat <<EOF >> $output
))
EOF

fi
