#!/usr/bin/env bash
"exec" "planck-c/build/planck" "--classpath=lib/test.check-0.10.0-alpha2.jar:planck-cljs/test" "--compile-opts" "@/compile-opts.edn" "$0" "$@"
(ns planck.unit-test
  (:require [cljs.test]
            [planck.test-runner]
            [planck.core :refer [exit]]))

(defmethod cljs.test/report [:cljs.test/default :end-run-tests] [m]
  (when-not (cljs.test/successful? m)
    (exit 1)))

(planck.test-runner/run-all-tests)
