#!/bin/bash

MARKDOWN_CLJ_VER="0.9.85"

MARKDOWN_CLJ_JAR=~/.m2/repository/markdown-clj/markdown-clj/$MARKDOWN_CLJ_VER/markdown-clj-$MARKDOWN_CLJ_VER.jar

if [ ! -f $MARKDOWN_CLJ_JAR ]; then
    pushd script
    lein deps
    popd
    # Shouldn't have to blow away cache. Perhaps this is a bug in Planck.
    rm -rf script/cache/*
fi

planck -c $MARKDOWN_CLJ_JAR -k script/cache script/build.cljs
