#!/bin/bash

echo '#import <Foundation/Foundation.h>' > CljsRuntime.m
echo "" > manifest.m
cd out
for file in `find . -name '*.js' -o -name '*.cljs' -o -name '*.cljc' -o -name '*.map'`
do 
file=${file:2}
xxd -i $file >> ../CljsRuntime.m
data_ref=${file//\//_}
data_ref=${data_ref//\./_}
data_ref=${data_ref//\$/_}
echo "@\"${file}\": @[[NSValue valueWithPointer:${data_ref}], [NSNumber numberWithInt:${data_ref}_len]]," >> ../manifest.m
done
cd ..
cat <<EOF >> CljsRuntime.m
#import "CljsRuntime.h"

@interface CljsRuntime()

@property (strong) NSDictionary* manifest;

@end

@implementation CljsRuntime

-(id)init {
    if ( self = [super init] ) {
        self.manifest = @{
EOF

cat manifest.m >> CljsRuntime.m

cat <<EOF >> CljsRuntime.m
    };
    return self;
}

-(NSString*)getSourceForPath:(NSString*)path {

    unsigned char* p =[((NSValue*)(self.manifest[path][0])) pointerValue];
    int len = [(NSNumber*)self.manifest[path][1] intValue];
    
    NSData* data = [NSData dataWithBytes:p
                                  length:len];
    
    NSString* rv =
    [[NSString alloc] initWithData:data
                          encoding:NSUTF8StringEncoding];
    
    return rv;
}
EOF
rm manifest.m
mv CljsRuntime.m ../../planck
