Vagrant.configure(2) do |config|

  config.vm.box = "nixos/nixos-17.09-x86_64"
  
  config.vm.provision "shell", inline: <<-SHELL
    nix-env -iA nixos.git nixos.clang nixos.gnumake nixos.cmake nixos.pkgconfig nixos.vim nixos.jdk nixos.maven nixos.webkitgtk nixos.glib nixos.pcre nixos.libzip nixos.icu nixos.curl nixos.zlib nixos.unzip
    #curl -O https://download.clojure.org/install/linux-install-1.9.0.315.sh
    #chmod +x linux-install-1.9.0.315.sh
    #sudo ./linux-install-1.9.0.315.sh
  SHELL

end
