#!/bin/bash

# Make sure we fail and exit on the command that actually failed.
set -e
set -o pipefail

# Previously was building using lein
#lein run -m clojure.main script/build.clj

# Build our own copy of ClojureScript compiler
CLJS_GIT_SHA1=2023353d635578a0666a50c3305bf92347185646
if [ ! -e clojurescript ]; then
   git clone https://github.com/clojure/clojurescript
   pushd clojurescript
   git reset --hard $CLJS_GIT_SHA1
   # Apply patches
   curl -L http://dev.clojure.org/jira/secure/attachment/15505/CLJS-1564-2.patch | git am -3
   curl -L http://dev.clojure.org/jira/secure/attachment/15507/CLJS-1577-2.patch | git am -3
   curl -L http://dev.clojure.org/jira/secure/attachment/15508/CLJS-1585-2.patch | git am -3
   script/uberjar
   popd
fi

CLJSC_CP=`lein classpath`:clojurescript/target/cljs.jar
java -cp $CLJSC_CP clojure.main script/build.clj
