#!/bin/bash

# Make sure we fail and exit on the command that actually failed.
set -e
set -o pipefail

# Previously was building using lein
#lein run -m clojure.main script/build.clj

# Build our own copy of ClojureScript compiler
CLJS_GIT_COMMIT=c31e91f89dab42d519e9051e630ac8011cafa8d7
if [ ! -e clojurescript ]; then
   git clone https://github.com/clojure/clojurescript
   pushd clojurescript
   git reset --hard $CLJS_GIT_COMMIT
   # Apply patches
   curl -L http://dev.clojure.org/jira/secure/attachment/15548/CLJS-1590v2.patch | git apply
   curl -L http://dev.clojure.org/jira/secure/attachment/15518/CLJS-1592.patch | git apply
   # Deal with the case when building in sandbox mode
   if [ -e ../profiles.clj ]; then
       export MAVEN_OPTS="-Dmaven.repo.local=../sandbox-m2"
       echo "{:dev {:local-repo \"../sandbox-m2\"}}" > profiles.clj
   fi
   script/uberjar
   popd
fi

CLJSC_CP=`lein classpath`:clojurescript/target/cljs.jar
java -cp $CLJSC_CP clojure.main script/build.clj
