#!/bin/bash

echo '#import <Foundation/Foundation.h>' > PLKBundledOut.m
echo "" > manifest.m
cd out
for file in `find . -name '*.js' -o -name '*.cljs' -o -name '*.cljc' -o -name '*.map'`
do 
file=${file:2}
xxd -i $file >> ../PLKBundledOut.m
data_ref=${file//\//_}
data_ref=${data_ref//\./_}
data_ref=${data_ref//\$/_}
echo "@\"${file}\": @[[NSValue valueWithPointer:${data_ref}], [NSNumber numberWithInt:${data_ref}_len]]," >> ../manifest.m
done
cd ..
cat <<EOF >> PLKBundledOut.m
#import "PLKBundledOut.h"

@interface PLKBundledOut()

@property (strong) NSDictionary* manifest;

@end

@implementation PLKBundledOut 

-(id)init {
    if ( self = [super init] ) {
        self.manifest = @{
EOF

cat manifest.m >> PLKBundledOut.m

cat <<EOF >> PLKBundledOut.m
    };
  }
  return self;
}

-(NSString*)getSourceForPath:(NSString*)path {

    NSValue* value = (NSValue*)(self.manifest[path][0]);
    if (!value) {
      return nil;
    }

    unsigned char* p =[value pointerValue];
    int len = [(NSNumber*)self.manifest[path][1] intValue];
    
    NSData* data = [NSData dataWithBytes:p
                                  length:len];
    
    NSString* rv =
    [[NSString alloc] initWithData:data
                          encoding:NSUTF8StringEncoding];
    
    return rv;
}

@end
EOF
rm manifest.m
mv PLKBundledOut.m ../planck
# We don't want git to suggest we commit this generated
# output, so we suppress it here.
git update-index --assume-unchanged ../planck/PLKBundledOut.m
