#!/usr/bin/env bash

# Handle case where LEIN_HOME has been set
if [ -n "$LEIN_HOME" ]; then
  export LEIN_HOME=../lein_home
fi

script/lein clean
if [ -z "$BUILD_PPA" ]; then
    rm -f jscomp.js
fi
rm -rf resources
rm -rf tools.reader
rm -rf clojurescript
script/clean-bundle
