#!/usr/bin/env bash

if [ "${VERBOSE_BUILD:-0}" == "1" ]; then
  set -x
fi

if [ -z "$BUILD_PPA" ]; then
    rm -f jscomp.js
fi
rm -rf out
rm -rf target
rm -rf resources
rm -rf tools.reader
rm -rf clojurescript
script/clean-bundle
